sudo: no
dist: stretch
group: edge
services:
  - docker

script:
  - >
    mkdir components &&
    cd components &&
    git clone https://github.com/micromaomao/fancy-lyric.git &&
    git clone https://github.com/micromaomao/leafvote.git &&
    git clone https://github.com/micromaomao/maowtm.org.git &&
    git clone https://github.com/micromaomao/schsrch.git &&
    cd ..
  - docker build . -t maowtm/maowtm --no-cache
  - cd components/maowtm.org/local-dev-cert && make && cd ../../..
  - >
    for cmd in \
      "cd maowtm.org && npm run test" \
      "cd schsrch && test/perpareDatabase.sh && npm run test"; do \
      docker-compose -f docker-compose-dev.yml up -d es mongo redis &&
      sleep 20 &&
      docker run --entrypoint=bash -t --user=www --network maowtmorg-docker_mw maowtm/maowtm -c "$cmd" &&
      docker-compose -f docker-compose-dev.yml down &&
      docker container prune -f && docker volume prune -f;
      if [ $? -ne 0 ]; then
        exit 1;
      fi;
    done;
  - >
    docker-compose -f docker-compose-dev.yml up -d es mongo redis &&
    sleep 20 &&
    docker run --entrypoint=bash --network maowtmorg-docker_mw -P3000:80 maowtm/maowtm -c "./maowtm.org/launcher.docker.js" </dev/null &;
    sleep 10 &&
    curl -vI 'http://127.0.0.1:3000'

deploy:
  provider: script
  script: echo "$DOCKERHUB_PASSWORD" | docker login -u "maowtm" --password-stdin && docker push maowtm/maowtm
  on:
    branch: master
