version: '3'
networks:
  mw:
    driver: bridge
services:
  www:
    container_name: mw-www
    image: maowtm/maowtm:latest
    # build: .
    networks:
      - mw
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: bash
    depends_on:
      - mongo
      - redis
      - es
    volumes:
      - ./components/maowtm.org/local-dev-cert:/usr/src/app/maowtm.org/local-dev-cert
      # - ./components/maowtm.org:/usr/src/app/maowtm.org
      # - ./components/maowtm.org/index.js:/usr/src/app/maowtm.org/index.js
      # - /usr/src/app/maowtm.org/node_modules
      # - ./components/schsrch/view:/usr/src/app/schsrch/view
      # - ./components/schsrch/test:/usr/src/app/schsrch/test
      # - ./components/schsrch/index.js:/usr/src/app/schsrch/index.js
      # - ./components/leafvote/view:/usr/src/app/leafvote/view
      # - ./components/maowtm.org/.well-known:/opt/.well-known
    deploy:
      restart_policy:
        condition: any
        delay: 1s
  mongo:
    container_name: mw-mongo
    image: mongo:latest
    networks:
      - mw
    volumes:
      - /data/db
      - /data/configdb
    command: ["--noauth"]
    deploy:
      restart_policy:
        condition: any
        delay: 1s
  redis:
    container_name: mw-redis
    image: redis:latest
    networks:
      - mw
    volumes:
      - /data
    deploy:
      restart_policy:
        condition: any
        delay: 1s
  es:
    container_name: mw-es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    networks:
      - mw
    volumes:
      - /usr/share/elasticsearch/data
    deploy:
      restart_policy:
        condition: any
        delay: 1s
