name: Build docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build script
        run: >
          mkdir components &&
          cd components &&
          git clone https://github.com/micromaomao/maowtm.org.git &&
          git clone https://github.com/micromaomao/schsrch.git &&
          git clone https://github.com/micromaomao/leafvote.git &&
          cd .. &&
          chmod u=rwX,go=rX -R . &&
          docker build . -t maowtm/maowtm --no-cache &&
          cd components/maowtm.org/local-dev-cert && make && cd ../../.. &&
          for cmd in \
            "cd maowtm.org && npm run test" \
            "cd schsrch && test/prepareDatabase.sh && npm run test"; do \
            docker-compose -f docker-compose-dev.yml up -d es mongo redis &&
            sleep 40 &&
            docker run --entrypoint=bash -t --user=www --network maowtmorg-docker_mw maowtm/maowtm -c "$cmd" &&
            docker-compose -f docker-compose-dev.yml down &&
            docker container prune -f && docker volume prune -f;
            if [ $? -ne 0 ]; then
              exit 1;
            fi;
          done;
          docker-compose -f docker-compose-dev.yml up -d es mongo redis;
          if [ $? -ne 0 ]; then
            exit 1;
          fi;
          sleep 40;
          docker run --entrypoint=bash --network maowtmorg-docker_mw -p 3000:80 -v $(pwd)/components/maowtm.org/local-dev-cert:/usr/src/app/maowtm.org/local-dev-cert maowtm/maowtm -c "rm ./maowtm.org/static/imgs/* -rf && ./maowtm.org/launcher.docker.js" </dev/null &
          sleep 40 &&
          curl -vI 'http://127.0.0.1:3000'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: >
          docker tag maowtm/maowtm ghcr.io/micromaomao/maowtm.org-docker &&
          docker push ghcr.io/micromaomao/maowtm.org-docker
